In [1]:
import numpy as np
np.random.seed(42)

dataset

In [2]:
# XOR:
xor_gate = np.array([[0, 0, 0], [0, 1, 1], [1, 0, 1], [1, 1, 0]])

# IRIS 3 especies
# columnas = [largo de sepalo, ancho de petalo] 0=setosa , 1=versicolor, 2 = virginica
iris = np.array([[4.7, 0.2, 0], [4.6, 0.2, 0], [7, 1.4, 1], [6.4, 1.5, 1], [6.3, 1.8, 2], [6.5, 2.2, 2]])

# creamos una entrada aleatoria
X = np.array([[7], [1.4]])
Y = np.array([[0], [1], [0]])

funciones

In [3]:
def sigmoid(x, derived=False):
  if derived:
    return sigmoid(x)*(1 - sigmoid(x))
  else:
    return 1/(1+np.exp(-x))

def MSE(y_true, y_pred, derived=False):
  if derived:
    return y_pred - y_true
  else:
    return np.square(y_true - y_pred).sum()/2

Perceptron multicapa

In [4]:
# tamaño de las capas
n_input, n_hidden, n_out = 2, 3, 3

# coeficiente de aprendizaje
alfa = 0.25

# inicializar pesos random dentro del rango de una distribucion normal
mean, stdev = 0, 0.1 # media, desviacion estandar
w_hidden = np.array([[0.1, 0.8], [0.7, 0.9], [0.5, 0.3]])
w_out = np.array([[0.3, 0.7, 0.5], [0.5, 0.1, 0.5], [0.2, 0.8, 0.9]])

# guardar error
error = []

Propagar

In [5]:
# operar en la capa oculta
sum_hidden = w_hidden.dot(X)
out_hidden = sigmoid(sum_hidden)
out_hidden

array([[0.86056613],
       [0.9978922 ],
       [0.98054492]])

In [6]:
# operar en la capa de salida
sum_out = w_out.dot(out_hidden)
out_out = sigmoid(sum_out)
out_out

array([[0.80953119],
       [0.73503975],
       [0.86446928]])

Calcular el ERROR de la red neuronal

In [7]:
error.append(MSE(Y, out_out))

Retropropagamos

In [8]:
# operamos en la capa de salida OUT

# calculamos el error inputado a cada neurona
dC_da_out = MSE(Y, out_out, derived=True)
dA_dz_out = sigmoid(sum_out, derived=True)
delta_out = dC_da_out * dA_dz_out
print(delta_out)

# calculamos el error inputado a cada parametro
dZ_dw_out = out_hidden
dC_dw_out = delta_out.dot(dZ_dw_out.T)

# actualizamos el valor de los pesos
w_out_new = w_out - alfa * dC_dw_out
w_out_new

[[ 0.12482197]
 [-0.05160268]
 [ 0.10128308]]


array([[0.27314561, 0.66886028, 0.46940161],
       [0.51110188, 0.11287348, 0.51264969],
       [0.1782098 , 0.7747326 , 0.87517185]])

In [9]:
# operamos en la capa oculta HIDDEN

# retropropagamos el error calculado en la capa de salida
delta_hidden = w_out.dot(delta_out) * sigmoid(sum_hidden, derived=True)
print(delta_hidden)

# calculamos el error inputado a cada parametro
dZ_dw_hidden = X
dC_dw_hidden = delta_hidden.dot(dZ_dw_hidden.T)

# # actualizamos el valor de los pesos
w_hidden_new = w_hidden - alfa * dC_dw_hidden
w_hidden_new

[[0.00623554]
 [0.00022694]
 [0.00142763]]


array([[0.08908781, 0.79781756],
       [0.69960286, 0.89992057],
       [0.49750164, 0.29950033]])

PROPAGAR y Calcular ERROR

In [10]:
# operar en la capa oculta
sum_hidden_new = w_hidden_new.dot(X)
out_hidden_new = sigmoid(sum_hidden_new)

# operar en la capa de salida
sum_out_new = w_out_new.dot(out_hidden_new)
out_out_new = sigmoid(sum_out_new)
print(out_out_new)

# calcular error
error.append(MSE(Y, out_out_new))

[[0.79574869]
 [0.74076636]
 [0.85601112]]


In [12]:
# el error disminuye
error

[0.7364259053437099, 0.7165865513801564]